<title>Promise methods</title>

<script id="Setup">

    const createPromise = (value, timeout = 1_000, willFail = false) => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (willFail) reject("Failure");
                resolve(value);
            }, timeout);
        });
    };

    const promises = [
        createPromise("First promise", 1_000),
        // createPromise("Second promise", 2_000, true),
        createPromise("Third promise", 3_000),
    ];

</script>

<script id="Promise methods">

    // promises.forEach(promise => promise.then(val => console.log(val)));

    // promises.map(promise => promise.then(console.log));



    // Promise.all(promises)
    //   .then(values => console.log(values))
    //   .catch(err => console.error(err));

    

    // Promise.race(promises)
    //   .then(val => console.log(val))
    //   .catch(err => console.error(err));



    /* Resolve/Reject static methods */
    // new Promise(resolve => resolve(42)).then(console.log);
    // Promise.resolve(42).then(console.log);

    /* both are Asynchronous tbh. */
    // const getAsyncNum = async () => 42;
    // const getPromisifiedNum = () => Promise.resolve(42);

    // getAsyncNum().then(console.log);
    // getPromisifiedNum().then(console.log);



    // new Promise((_, reject) => reject("Ooopsie")).then(console.error);
    // Promise.reject("Ooopsie").then(console.error);

    // const getAsyncError = async () => { throw new Error("Ooopsie"); };
    // const getPromisifiedError = () => Promise.reject("Ooopsie");

    // getAsyncError().catch(console.error);
    // getPromisifiedError().catch(console.error);

</script>

<script id="Promisification with static methods">

    // const logIn = (login, password) => {
    //     if (login === "admin" && password === "admin") {
    //         return Promise.resolve("Access granted!");
    //     }

    //     return Promise.reject("No permissions");
    // };

    // // logIn("admin", "admin")
    // logIn("admin", "not-admin")
    //   .then(console.log)
    //   .catch(console.error);


    /* Async/Await + try/catch */
    // const asyncFn = async () => {
    //   const pwd = prompt("Provide a password");
    //   try {
    //     const resultMessage = await logIn("admin", pwd);

    //     console.log("Result:", resultMessage);
    //   } catch (error) {
    //     console.error(error);
    //   }
    // };


    /* Async/Await + Callbacks */
    // const asyncFn = async () => {
    //     const pwd = prompt("Provide a password");
    //     const resultMessage = await logIn("admin", pwd).catch(console.error);

    //     console.log("Result:", resultMessage);
    // };

    // asyncFn();

</script>
